# Generated by Django 5.1.6 on 2025-03-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
