# Generated by Django 5.1.6 on 2025-03-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0002_camera_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
