# Generated by Django 5.1.6 on 2025-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0003_camera_latitude_camera_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
