# Generated by Django 5.1.6 on 2025-03-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0004_detectionevent_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='longitude',
        ),
    ]
