# Generated by Django 5.1.6 on 2025-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0005_remove_camera_latitude_remove_camera_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
