# Generated by Django 5.1.6 on 2025-03-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0006_camera_latitude_camera_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Cámara', 'verbose_name_plural': 'Cámaras'},
        ),
        migrations.AlterModelOptions(
            name='detectionevent',
            options={'verbose_name': 'Evento de detección', 'verbose_name_plural': 'Eventos de detección'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
