# Generated by Django 5.1.6 on 2025-03-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_userprofile_delete_usercamera'),
        ('reconocimiento', '0002_camera_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.camera'),
        ),
    ]
