# Generated by Django 5.1.6 on 2025-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_remove_userprofile_fcm_token_userprofile_email_and_more'),
        ('reconocimiento', '0006_camera_latitude_camera_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='camera',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cameras',
            field=models.ManyToManyField(blank=True, to='reconocimiento.camera'),
        ),
    ]
